### ISSUE TITLE
Make things more configurable

### ISSUE THREAD

**Issue by willdurand** [voxpupuli/puppet-blacksmith#2]
Heya!

Thank you for this gem, really useful. However, I think it is a bit too much opinionated.
IMO we should be able to configure:
- the "bump commit" message;
- the tag pattern (I don't use `v` in my tags).

I guess the `~/puppetforge.yml` file is a good start. We could add two new parameters such as `bump_commit_message` and `tag_pattern`:

``` yaml

---
url: ...
username: ...
password: ...
git:
  bump_commit_message: "Bump version"
  tag_pattern: "v{version_number}"
```

WDYT?

William
